Working with Date Values

In [1]:
import pandas as pd

url = "../datasets/file2.json"
df = pd.read_json(url)

df["doj"] = [
    "2025-01-10",
    "2025-02-10",
    "2025-03-10",
    "2025-04-10",
    "2025-05-10"
]

df["doj"].dtype

In [2]:
df["doj"] = pd.to_datetime(df["doj"])

df["year"] = df["doj"].dt.year
df["month"] = df["doj"].dt.month
df["day"] = df["doj"].dt.day
df["day_name"] = df["doj"].dt.day_name()

df

       name  roll no  marks        doj  year  month  day  day_name
0   dheeraj      123     10 2025-01-10  2025      1   10    Friday
1     kunal     1234     20 2025-02-10  2025      2   10    Monday
2  abhishek    12345     30 2025-03-10  2025      3   10    Monday
3   praveen    12356     40 2025-04-10  2025      4   10  Thursday
4    anjali  1234567     50 2025-05-10  2025      5   10  Saturday

In [3]:
df["date_after_20_days"] = df["doj"] + pd.to_timedelta(20, unit="D")

df

,name,roll no,marks,doj,year,month,day,day_name,date_after_20_days
0,dheeraj,123,10,2025-01-10,2025,1,10,Friday,2025-01-30
1,kunal,1234,20,2025-02-10,2025,2,10,Monday,2025-03-02
2,abhishek,12345,30,2025-03-10,2025,3,10,Monday,2025-03-30
3,praveen,12356,40,2025-04-10,2025,4,10,Thursday,2025-04-30
4,anjali,1234567,50,2025-05-10,2025,5,10,Saturday,2025-05-30

Handling Missing Values

In [4]:
import pandas as pd

url = "../datasets/file2.json"
df = pd.read_json(url)

df.isnull()

    name  roll no  marks
0  False    False  False
1  False    False  False
2  False    False  False
3  False    False  False
4  False    False  False

In [5]:
df.isnull().sum()

name       0
roll no    0
marks      0
dtype: int64

In [6]:
df.dropna()

       name  roll no  marks
0   dheeraj      123     10
1     kunal     1234     20
2  abhishek    12345     30
3   praveen    12356     40
4    anjali  1234567     50

In [7]:
df.dropna(axis=1)

       name  roll no  marks
0   dheeraj      123     10
1     kunal     1234     20
2  abhishek    12345     30
3   praveen    12356     40
4    anjali  1234567     50

In [8]:
df.fillna(0)

       name  roll no  marks
0   dheeraj      123     10
1     kunal     1234     20
2  abhishek    12345     30
3   praveen    12356     40
4    anjali  1234567     50

In [9]:
df.fillna(100)

       name  roll no  marks
0   dheeraj      123     10
1     kunal     1234     20
2  abhishek    12345     30
3   praveen    12356     40
4    anjali  1234567     50

In [10]:
df["roll no"] = df["roll no"].fillna(200)
df["marks"] = df["marks"].fillna(100)

df

       name  roll no  marks
0   dheeraj      123     10
1     kunal     1234     20
2  abhishek    12345     30
3   praveen    12356     40
4    anjali  1234567     50

In [11]:
df = pd.read_json(url)

marks_mean = df["marks"].mean()
df["marks"] = df["marks"].fillna(marks_mean)

df

       name  roll no  marks
0   dheeraj      123     10
1     kunal     1234     20
2  abhishek    12345     30
3   praveen    12356     40
4    anjali  1234567     50